version: '3.8'

services:
  logstash_postgres_input:
    image: postgres:9.6-alpine
    container_name: logstash_postgres_input
    depends_on:
      - logstash_postgres_output
    ports:
      - 5432:5432
    networks:
      - internal
    environment:
      POSTGRES_DB: test_input_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgadmin
  logstash_postgres_output:
    image: postgres:9.6-alpine
    container_name: logstash_postgres_output
    ports:
      - 5433:5432
    networks:
      - internal
    environment:
      POSTGRES_DB: test_output_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgadmin

networks:
  internal:
    driver: bridge